# Generated by Django 5.0.6 on 2024-08-29 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_purchase_address_purchase_email_purchase_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='purchase_count',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
